-- 0004_country_continent.sql
-- Country -> continent lookup (single source of truth, used by the sync and the
-- migration backfill via continents_of()). Keys are lower-cased country names as
-- ClinicalTrials.gov spells them, plus common variants. Unknown countries map to
-- 'Other' — add a row here (and re-run migrations) to fix one.
BEGIN;

CREATE TABLE IF NOT EXISTS ref_country_continent (
  country_key  text PRIMARY KEY,   -- lower(btrim(country))
  continent    text NOT NULL
);

INSERT INTO ref_country_continent (country_key, continent) VALUES
  ('united states', 'North America'),
  ('usa', 'North America'),
  ('u.s.a.', 'North America'),
  ('canada', 'North America'),
  ('mexico', 'North America'),
  ('puerto rico', 'North America'),
  ('guatemala', 'North America'),
  ('costa rica', 'North America'),
  ('panama', 'North America'),
  ('dominican republic', 'North America'),
  ('cuba', 'North America'),
  ('honduras', 'North America'),
  ('el salvador', 'North America'),
  ('nicaragua', 'North America'),
  ('jamaica', 'North America'),
  ('haiti', 'North America'),
  ('belize', 'North America'),
  ('bahamas', 'North America'),
  ('barbados', 'North America'),
  ('trinidad and tobago', 'North America'),
  ('bermuda', 'North America'),
  ('martinique', 'North America'),
  ('guadeloupe', 'North America'),
  ('virgin islands (u.s.)', 'North America'),
  ('united states minor outlying islands', 'North America'),
  ('antigua and barbuda', 'North America'),
  ('saint lucia', 'North America'),
  ('grenada', 'North America'),
  ('dominica', 'North America'),
  ('cayman islands', 'North America'),
  ('aruba', 'North America'),
  ('curaçao', 'North America'),
  ('curacao', 'North America'),
  ('greenland', 'North America'),
  ('saint kitts and nevis', 'North America'),
  ('saint vincent and the grenadines', 'North America'),
  ('netherlands antilles', 'North America'),
  ('brazil', 'South America'),
  ('argentina', 'South America'),
  ('chile', 'South America'),
  ('colombia', 'South America'),
  ('peru', 'South America'),
  ('venezuela', 'South America'),
  ('venezuela, bolivarian republic of', 'South America'),
  ('ecuador', 'South America'),
  ('uruguay', 'South America'),
  ('paraguay', 'South America'),
  ('bolivia', 'South America'),
  ('bolivia, plurinational state of', 'South America'),
  ('guyana', 'South America'),
  ('suriname', 'South America'),
  ('french guiana', 'South America'),
  ('united kingdom', 'Europe'),
  ('uk', 'Europe'),
  ('great britain', 'Europe'),
  ('england', 'Europe'),
  ('scotland', 'Europe'),
  ('wales', 'Europe'),
  ('northern ireland', 'Europe'),
  ('ireland', 'Europe'),
  ('france', 'Europe'),
  ('germany', 'Europe'),
  ('spain', 'Europe'),
  ('italy', 'Europe'),
  ('portugal', 'Europe'),
  ('netherlands', 'Europe'),
  ('belgium', 'Europe'),
  ('luxembourg', 'Europe'),
  ('austria', 'Europe'),
  ('switzerland', 'Europe'),
  ('denmark', 'Europe'),
  ('sweden', 'Europe'),
  ('norway', 'Europe'),
  ('finland', 'Europe'),
  ('iceland', 'Europe'),
  ('poland', 'Europe'),
  ('czech republic', 'Europe'),
  ('czechia', 'Europe'),
  ('slovakia', 'Europe'),
  ('hungary', 'Europe'),
  ('romania', 'Europe'),
  ('bulgaria', 'Europe'),
  ('greece', 'Europe'),
  ('croatia', 'Europe'),
  ('slovenia', 'Europe'),
  ('serbia', 'Europe'),
  ('serbia and montenegro', 'Europe'),
  ('bosnia and herzegovina', 'Europe'),
  ('north macedonia', 'Europe'),
  ('macedonia', 'Europe'),
  ('macedonia, the former yugoslav republic of', 'Europe'),
  ('montenegro', 'Europe'),
  ('albania', 'Europe'),
  ('estonia', 'Europe'),
  ('latvia', 'Europe'),
  ('lithuania', 'Europe'),
  ('ukraine', 'Europe'),
  ('belarus', 'Europe'),
  ('moldova', 'Europe'),
  ('moldova, republic of', 'Europe'),
  ('republic of moldova', 'Europe'),
  ('russia', 'Europe'),
  ('russian federation', 'Europe'),
  ('malta', 'Europe'),
  ('cyprus', 'Europe'),
  ('liechtenstein', 'Europe'),
  ('monaco', 'Europe'),
  ('andorra', 'Europe'),
  ('san marino', 'Europe'),
  ('kosovo', 'Europe'),
  ('faroe islands', 'Europe'),
  ('gibraltar', 'Europe'),
  ('holy see (vatican city state)', 'Europe'),
  ('jersey', 'Europe'),
  ('guernsey', 'Europe'),
  ('isle of man', 'Europe'),
  ('former serbia and montenegro', 'Europe'),
  ('south africa', 'Africa'),
  ('egypt', 'Africa'),
  ('nigeria', 'Africa'),
  ('kenya', 'Africa'),
  ('morocco', 'Africa'),
  ('tunisia', 'Africa'),
  ('algeria', 'Africa'),
  ('ghana', 'Africa'),
  ('ethiopia', 'Africa'),
  ('tanzania', 'Africa'),
  ('tanzania, united republic of', 'Africa'),
  ('uganda', 'Africa'),
  ('zimbabwe', 'Africa'),
  ('zambia', 'Africa'),
  ('cameroon', 'Africa'),
  ('senegal', 'Africa'),
  ('sudan', 'Africa'),
  ('south sudan', 'Africa'),
  ('ivory coast', 'Africa'),
  ('côte d''ivoire', 'Africa'),
  ('cote d''ivoire', 'Africa'),
  ('cote d ivoire', 'Africa'),
  ('democratic republic of the congo', 'Africa'),
  ('congo, the democratic republic of the', 'Africa'),
  ('congo', 'Africa'),
  ('burkina faso', 'Africa'),
  ('mali', 'Africa'),
  ('niger', 'Africa'),
  ('benin', 'Africa'),
  ('togo', 'Africa'),
  ('guinea', 'Africa'),
  ('guinea-bissau', 'Africa'),
  ('sierra leone', 'Africa'),
  ('liberia', 'Africa'),
  ('gambia', 'Africa'),
  ('mauritania', 'Africa'),
  ('libya', 'Africa'),
  ('libyan arab jamahiriya', 'Africa'),
  ('botswana', 'Africa'),
  ('namibia', 'Africa'),
  ('mozambique', 'Africa'),
  ('rwanda', 'Africa'),
  ('burundi', 'Africa'),
  ('malawi', 'Africa'),
  ('madagascar', 'Africa'),
  ('mauritius', 'Africa'),
  ('réunion', 'Africa'),
  ('reunion', 'Africa'),
  ('seychelles', 'Africa'),
  ('angola', 'Africa'),
  ('gabon', 'Africa'),
  ('equatorial guinea', 'Africa'),
  ('central african republic', 'Africa'),
  ('chad', 'Africa'),
  ('eritrea', 'Africa'),
  ('djibouti', 'Africa'),
  ('somalia', 'Africa'),
  ('lesotho', 'Africa'),
  ('eswatini', 'Africa'),
  ('swaziland', 'Africa'),
  ('cape verde', 'Africa'),
  ('cabo verde', 'Africa'),
  ('comoros', 'Africa'),
  ('mayotte', 'Africa'),
  ('sao tome and principe', 'Africa'),
  ('china', 'Asia'),
  ('india', 'Asia'),
  ('japan', 'Asia'),
  ('south korea', 'Asia'),
  ('korea, republic of', 'Asia'),
  ('republic of korea', 'Asia'),
  ('korea', 'Asia'),
  ('north korea', 'Asia'),
  ('korea, democratic people''s republic of', 'Asia'),
  ('taiwan', 'Asia'),
  ('hong kong', 'Asia'),
  ('macau', 'Asia'),
  ('macao', 'Asia'),
  ('singapore', 'Asia'),
  ('malaysia', 'Asia'),
  ('thailand', 'Asia'),
  ('vietnam', 'Asia'),
  ('viet nam', 'Asia'),
  ('indonesia', 'Asia'),
  ('philippines', 'Asia'),
  ('pakistan', 'Asia'),
  ('bangladesh', 'Asia'),
  ('sri lanka', 'Asia'),
  ('nepal', 'Asia'),
  ('bhutan', 'Asia'),
  ('maldives', 'Asia'),
  ('israel', 'Asia'),
  ('turkey', 'Asia'),
  ('türkiye', 'Asia'),
  ('turkiye', 'Asia'),
  ('saudi arabia', 'Asia'),
  ('united arab emirates', 'Asia'),
  ('iran', 'Asia'),
  ('iran, islamic republic of', 'Asia'),
  ('iraq', 'Asia'),
  ('jordan', 'Asia'),
  ('lebanon', 'Asia'),
  ('kuwait', 'Asia'),
  ('qatar', 'Asia'),
  ('oman', 'Asia'),
  ('bahrain', 'Asia'),
  ('kazakhstan', 'Asia'),
  ('uzbekistan', 'Asia'),
  ('kyrgyzstan', 'Asia'),
  ('tajikistan', 'Asia'),
  ('turkmenistan', 'Asia'),
  ('georgia', 'Asia'),
  ('armenia', 'Asia'),
  ('azerbaijan', 'Asia'),
  ('mongolia', 'Asia'),
  ('myanmar', 'Asia'),
  ('cambodia', 'Asia'),
  ('laos', 'Asia'),
  ('lao people''s democratic republic', 'Asia'),
  ('brunei', 'Asia'),
  ('brunei darussalam', 'Asia'),
  ('timor-leste', 'Asia'),
  ('east timor', 'Asia'),
  ('afghanistan', 'Asia'),
  ('syria', 'Asia'),
  ('syrian arab republic', 'Asia'),
  ('yemen', 'Asia'),
  ('palestine', 'Asia'),
  ('palestinian territory, occupied', 'Asia'),
  ('palestinian territories', 'Asia'),
  ('state of palestine', 'Asia'),
  ('australia', 'Oceania'),
  ('new zealand', 'Oceania'),
  ('fiji', 'Oceania'),
  ('papua new guinea', 'Oceania'),
  ('samoa', 'Oceania'),
  ('tonga', 'Oceania'),
  ('vanuatu', 'Oceania'),
  ('solomon islands', 'Oceania'),
  ('new caledonia', 'Oceania'),
  ('french polynesia', 'Oceania'),
  ('guam', 'Oceania'),
  ('northern mariana islands', 'Oceania'),
  ('american samoa', 'Oceania'),
  ('micronesia, federated states of', 'Oceania'),
  ('palau', 'Oceania'),
  ('marshall islands', 'Oceania'),
  ('kiribati', 'Oceania'),
  ('nauru', 'Oceania'),
  ('tuvalu', 'Oceania'),
  ('cook islands', 'Oceania')
ON CONFLICT (country_key) DO UPDATE SET continent = EXCLUDED.continent;

-- Continent of one country ('Other' if unknown).
CREATE OR REPLACE FUNCTION continent_of(c text) RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT coalesce(
    (SELECT continent FROM ref_country_continent WHERE country_key = lower(btrim(c))),
    'Other')
$$;

-- Distinct continents for a list of countries (sorted; empty list -> '{}').
CREATE OR REPLACE FUNCTION continents_of(cs text[]) RETURNS text[]
LANGUAGE sql STABLE AS $$
  SELECT coalesce(array_agg(DISTINCT continent_of(x) ORDER BY continent_of(x)), '{}')
    FROM unnest(coalesce(cs, '{}')) AS x
   WHERE coalesce(btrim(x), '') <> ''
$$;

COMMIT;
